### ISSUE TITLE
CRUD Tournament and Rounds

### ISSUE THREAD

**Issue by jcazevedo** [jcazevedo/pawned#5] opened 2012-03-15 21:44 UTC
Implement the CRUD operations for the Tournament and Round models.

**Comment by saleiro** [comment] 2012-03-16 09:47
and this one.

**Comment by maharifu** [comment] 2012-03-16 10:22
This has to include a Tiebreaker model. Should it be in a separate issue?

**Comment by jcazevedo** [comment] 2012-03-16 11:10
I think we shouldn't include the Tiebreaker model for this milestone, yet. If necessary, we can open a separate issue for that later.

**Comment by maharifu** [comment] 2012-03-16 11:30
But the problem is that if you create a tournament now and there is a tie, you'll need some way to solve it.

**Comment by saleiro** [comment] 2012-03-16 11:36
For release 12.04 we are going to use the same framework as we were using until now. Therefore the ranking on each round should be manually updated.

**Comment by jcazevedo** [comment] 2012-03-16 11:41
Yeah. You solve the ties by hand. :)

**Comment by maharifu** [comment] 2012-03-16 11:59
Yes, but how? Do we introduce a Standings model to tell where everyone is on the tournament?

My understanding is that we could have a Tiebreaker model that would be filled by hand for 12.03 and automatic by 12.05 :p

**Comment by jcazevedo** [comment] 2012-03-16 12:04
You're right. We should have a Standings model to associate with each round, even if we have a Tiebreaker model.

**Comment by jcazevedo** [comment] 2012-03-16 12:08
Created an [issue](https://github.com/jcazevedo/pawned/issues/9) for that.

**Comment by maharifu** [comment] 2012-04-17 22:44
I think this is ready for this release. I'm closing this one for now.

**Closed as completed by maharifu** 2012-04-17 22:44 UTC
